/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { TrainingWhereUniqueInput } from "../../training/base/TrainingWhereUniqueInput";
import { ExerciseListRelationFilter } from "../../exercise/base/ExerciseListRelationFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TrainingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TrainingWhereUniqueInput)
  @IsOptional()
  @Field(() => TrainingWhereUniqueInput, {
    nullable: true,
  })
  trainings?: TrainingWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ExerciseListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExerciseListRelationFilter)
  @IsOptional()
  @Field(() => ExerciseListRelationFilter, {
    nullable: true,
  })
  exercises?: ExerciseListRelationFilter;
}

export { UserWhereInput as UserWhereInput };
